---
output: github_document
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

# dynparam

```{r, message = FALSE, error = FALSE, warning = FALSE}
library(tidyverse)
library(dynparam)
```

```{r, echo=FALSE}
cat <- function(x) {
  base::cat(
    "```yaml\n",
    x, "\n", 
    "```",
    sep = ""
  )
}
```

## Integer parameter
```{r}
param <- integer_parameter(
  id = "num_iter", 
  default = 100L,
  distribution = expuniform_distribution(lower = 1L, upper = 10000L),
  description = "Number of iterations"
)
param
```

It can be transformed to a list, then to a yaml:
```{r comment = "", results = "asis"}
ya <- yaml::as.yaml(as.list(param))
cat(ya)
```

And back:
```{r}
as_parameter(yaml::yaml.load(ya))
```

## Numeric parameter
```{r}
param <- numeric_parameter(
  id = "delta", 
  default = c(4.5, 2.4, 1.9), 
  distribution = normal_distribution(mean = 5, sd = 1),
  description = "Multiplying factors"
)
param
```

As yaml:
```{r comment = "", results = "asis"}
cat(yaml::as.yaml(as.list(param)))
```

## Character parameter
```{r}
param <- character_parameter(
  id = "method", 
  default = "kendall",
  values = c("kendall", "spearman", "pearson"), 
  description = "Correlation method"
)
param
```

As yaml:
```{r comment = "", results = "asis"}
cat(yaml::as.yaml(as.list(param)))
```

## Logical parameter
```{r}
param <- logical_parameter(
  id = "inverse",
  default = TRUE, 
  description = "Inversion parameter"
)
param
```

As yaml:
```{r comment = "", results = "asis"}
cat(yaml::as.yaml(as.list(param)))
```

## Subset parameter
```{r}
param <- subset_parameter(
 id = "dimreds",
 default = c("pca", "mds"),
 values = c("pca", "mds", "tsne", "umap", "ica"),
 description = "Which dimensionality reduction methods to apply (can be multiple)"
)
param
```

As yaml:
```{r comment = "", results = "asis"}
cat(yaml::as.yaml(as.list(param)))
```

## Range parameter
```{r}
param <- range_parameter(
  id = "ks",
  default = c(3L, 15L),
  lower_distribution = uniform_distribution(1L, 5L),
  upper_distribution = uniform_distribution(10L, 20L),
  description = "The numbers of clusters to be evaluated."
)
param
```

As yaml:
```{r comment = "", results = "asis"}
cat(yaml::as.yaml(as.list(param)))
```

## Example of parameter set
```{r}
parameters <- parameter_set(
  integer_parameter(
    id = "num_iter",
    default = 100L,
    distribution = expuniform_distribution(lower = 1L, upper = 10000L),
    description = "Number of iterations"
  ),

  numeric_parameter(
    id = "delta",
    default = c(4.5, 2.4, 1.9),
    distribution = normal_distribution(mean = 5, sd = 1),
    description = "Multiplying factors"
  ),

  character_parameter(
    id = "method",
    default = "kendall",
    values = c("kendall", "spearman", "pearson"),
    description = "Correlation method"
  ),

  logical_parameter(
    id = "inverse",
    default = TRUE,
    description = "Inversion parameter"
  ),

  subset_parameter(
    id = "dimreds",
    default = c("pca", "mds"),
    values = c("pca", "mds", "tsne", "umap", "ica"),
    description = "Which dimensionality reduction methods to apply (can be multiple)"
  ),
  
  range_parameter(
    id = "ks",
    default = c(3L, 15L),
    lower_distribution = uniform_distribution(1L, 5L),
    upper_distribution = uniform_distribution(10L, 20L),
    description = "The numbers of clusters to be evaluated",
    as_integer = TRUE
  ),

  range_parameter(
    id = "quantiles",
    default = c(0.15, 0.90),
    lower_distribution = uniform_distribution(0, .4),
    upper_distribution = uniform_distribution(.6, 1),
    description = "Quantile cutoff range",
    as_integer = FALSE
  ),
  
  forbidden = "inverse == (method == 'kendall')"
)
```

As paramhelper object:
```{r}
paramset <- as_paramhelper(parameters)

paramset %>%
  ParamHelpers::generateDesign(n = 1) %>% 
  ParamHelpers::dfRowToList(paramset, 1) %>% 
  ParamHelpers::trafoValue(paramset, .)
```

As yaml:
```{r comment = "", results = "asis"}
cat(yaml::as.yaml(as.list(parameters)))
```
